export const ADD_TARGET_CURRENCY = 'ADD_TARGET_CURRENCY'
export const SET_ALL_CURRENCIES = 'SET_ALL_CURRENCIES'
export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY'
export const SET_ALL_EXCHANGE_RATES = 'SET_ALL_EXCHANGE_RATES'
export const SET_TARGET_CURRENCY = 'SET_TARGET_CURRENCY'

